# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCaesar < Formula
  desc "Encrypt/decrypt files passwordlessly using GitHub's public key."
  homepage "https://github.com/yoshi389111/git-caesar"
  version "0.0.8"

  on_macos do
    url "https://github.com/yoshi389111/git-caesar/releases/download/v0.0.8/git-caesar_0.0.8_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "da5659e82c95f7c3de3a24138511f2516d3f9bb4fe49c47bdce6d291ebcd2566"

    def install
      bin.install "git-caesar"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yoshi389111/git-caesar/releases/download/v0.0.8/git-caesar_0.0.8_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "834e58f246d8167d5122516c2d6c8a981aca503ff6497ca7e9b1394f1f5e8249"
      def install
        bin.install "git-caesar"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/yoshi389111/git-caesar/releases/download/v0.0.8/git-caesar_0.0.8_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "ed950732e9dbea343bc4e7339e51d2f2c152619831855a895a3eab1d25c782b5"
      def install
        bin.install "git-caesar"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yoshi389111/git-caesar/releases/download/v0.0.8/git-caesar_0.0.8_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "950c941ddd9c9a2dbc6cabadeb450e38965236a3f2f20dfba609195d8ee5ed9d"
      def install
        bin.install "git-caesar"
      end
    end
  end

  test do
    system "#{bin}/git-caesar --version"
  end
end
