# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCaesar < Formula
  desc "Encrypt/decrypt files passwordlessly using GitHub's public key."
  homepage "https://github.com/yoshi389111/git-caesar"
  version "1.0.0"

  on_macos do
    url "https://github.com/yoshi389111/git-caesar/releases/download/v1.0.0/git-caesar_1.0.0_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "42399ff940fa7358f9e8ffca403712855bdc33a3b8243b7163d982d83e7bca9c"

    def install
      bin.install "git-caesar"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yoshi389111/git-caesar/releases/download/v1.0.0/git-caesar_1.0.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "7675120f67bbf375d5da2b3e65a67df7b631140841a845f3f37d23a4374622f0"
      def install
        bin.install "git-caesar"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/yoshi389111/git-caesar/releases/download/v1.0.0/git-caesar_1.0.0_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "b05017d8ec04b61b7a6ab971cbdeeca20e6adde7ac44d8266e1ed5e8cf9caede"
      def install
        bin.install "git-caesar"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yoshi389111/git-caesar/releases/download/v1.0.0/git-caesar_1.0.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "57daf8b1ea55687eb7a4aa59c13efc0cd967f79751b0adebede7057a5e264d6f"
      def install
        bin.install "git-caesar"
      end
    end
  end

  test do
    system "#{bin}/git-caesar --version"
  end
end
